#__________________________________________________________________________________________________
function(add_catalog_recursive catalog group_catalog source_files)
    file(GLOB children RELATIVE ${catalog} ${catalog}/*)
    foreach(child ${children})
        if(IS_DIRECTORY ${catalog}/${child})
            add_catalog_recursive(${catalog}/${child} ${group_catalog}/${child} ${source_files})
        else()
            get_filename_component(extension ${child} EXT)
            if (NOT extension STREQUAL "")
                string(REGEX MATCHALL "^.*.[h|cpp|qml]" out ${extension})
                if (NOT out STREQUAL "")
                    if(MSVC)
                        string(REPLACE "/" "\\" group_catalog_name ${group_catalog})   
                    else()
                        set(group_catalog_name ${group_catalog})
                    endif()
                    set(filename ${catalog}/${child})
                    source_group(${group_catalog_name} FILES ${filename})
                    set(${source_files} ${${source_files}} ${filename})
                endif()    
            endif()
        endif()        
    endforeach()
    set(${source_files} ${${source_files}} PARENT_SCOPE)
endfunction(add_catalog_recursive)

function(add_sources_from_catalog catalog group_catalog source_files)
    file(GLOB children RELATIVE ${catalog} ${catalog}/*)
    foreach(child ${children})
        get_filename_component(extension ${child} EXT)
        if (NOT extension STREQUAL "")
            string(REGEX MATCHALL "^.*.[h|cpp|qml]" out ${extension})
            if (NOT out STREQUAL "")
                if(MSVC)
                    string(REPLACE "/" "\\" group_catalog_name ${group_catalog})   
                else()
                    set(group_catalog_name ${group_catalog})
                endif()
                set(filename ${catalog}/${child})
                source_group(${group_catalog_name} FILES ${filename})
                set(${source_files} ${${source_files}} ${filename})
            endif()    
        endif()        
    endforeach()
    set(${source_files} ${${source_files}} PARENT_SCOPE)
endfunction(add_sources_from_catalog)

#__________________________________________________________________________________________________
macro(copy_directory dir_from dir_to)
    file(GLOB_RECURSE files_list "${dir_from}*")
    file(COPY ${files_list} DESTINATION ${dir_to})  
endmacro()
